trigger:
- main

pool:
  name: 'agent-pool'

steps:
# Login to Azure Container Registry and build/push Docker image
- task: AzureCLI@2
  inputs:
    azureSubscription: 'new-connection'
    scriptType: 'ps'  # Using PowerShell
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login -n mylabacr12
      docker build -t mylabacr12.azurecr.io/web-game:tag 2048-game
      docker push mylabacr12.azurecr.io/web-game:tag

# Check if app-deploy.yaml exists (PowerShell version for Windows agent)
- powershell: |
    if (Test-Path "01_kubernetes_aks\app-deploy.yaml") {
        Write-Output "File exists: 01_kubernetes_aks\app-deploy.yaml"
    } else {
        Write-Error "Error: File not found!"
        exit 1
    }
  displayName: 'Check if app-deploy.yaml exists'


- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'new-connection'
    azureResourceGroup: 'avi-vm_group'
    kubernetesCluster: 'mylab-aks'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'new-connection'
    azureContainerRegistry: 'mylabacr12.azurecr.io'
    forceUpdate: false
